spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      pool-name: SpringHickariPool
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect